import "./globals.css";
import "swiper/css";
import { plus_jakarta_sans } from "@/constants/Fonts";
import Providers from "./Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${plus_jakarta_sans.className} bg-[#F6F7F9]`}>
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
