import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";

export const metadata = {
  title: "Car-Rent App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
